//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsieJavaScriptEngine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MsieJavaScriptEngine.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; must be a non-empty string..
        /// </summary>
        internal static string Common_ArgumentIsEmpty {
            get {
                return ResourceManager.GetString("Common_ArgumentIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; must be a non-nullable..
        /// </summary>
        internal static string Common_ArgumentIsNull {
            get {
                return ResourceManager.GetString("Common_ArgumentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; not exist..
        /// </summary>
        internal static string Common_FileNotExist {
            get {
                return ResourceManager.GetString("Common_FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null..
        /// </summary>
        internal static string Common_ValueIsNull {
            get {
                return ResourceManager.GetString("Common_ValueIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string ErrorDetails_Category {
            get {
                return ResourceManager.GetString("ErrorDetails_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column number.
        /// </summary>
        internal static string ErrorDetails_ColumnNumber {
            get {
                return ResourceManager.GetString("ErrorDetails_ColumnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine mode.
        /// </summary>
        internal static string ErrorDetails_EngineMode {
            get {
                return ResourceManager.GetString("ErrorDetails_EngineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code.
        /// </summary>
        internal static string ErrorDetails_ErrorCode {
            get {
                return ResourceManager.GetString("ErrorDetails_ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line number.
        /// </summary>
        internal static string ErrorDetails_LineNumber {
            get {
                return ResourceManager.GetString("ErrorDetails_LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string ErrorDetails_Message {
            get {
                return ResourceManager.GetString("ErrorDetails_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source fragment.
        /// </summary>
        internal static string ErrorDetails_SourceFragment {
            get {
                return ResourceManager.GetString("ErrorDetails_SourceFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource with name &apos;{0}&apos; is null..
        /// </summary>
        internal static string Resources_ResourceIsNull {
            get {
                return ResourceManager.GetString("Resources_ResourceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveScript dispatcher is not initialized..
        /// </summary>
        internal static string Runtime_ActiveScriptDispatcherNotInitialized {
            get {
                return ResourceManager.GetString("Runtime_ActiveScriptDispatcherNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function name &apos;{0}&apos; is forbidden, as is contained in the list of reserved words of JavaScript language..
        /// </summary>
        internal static string Runtime_FunctionNameIsForbidden {
            get {
                return ResourceManager.GetString("Runtime_FunctionNameIsForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function with the name &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Runtime_FunctionNotExist {
            get {
                return ResourceManager.GetString("Runtime_FunctionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the function parameters &apos;{0}&apos; has a type `{1}`, which is not supported..
        /// </summary>
        internal static string Runtime_FunctionParameterTypeNotSupported {
            get {
                return ResourceManager.GetString("Runtime_FunctionParameterTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function name &apos;{0}&apos; has incorrect format..
        /// </summary>
        internal static string Runtime_InvalidFunctionNameFormat {
            get {
                return ResourceManager.GetString("Runtime_InvalidFunctionNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parser you passed implements neither `IActiveScriptParse32` nor `IActiveScriptParse64`..
        /// </summary>
        internal static string Runtime_InvalidParserImplementationError {
            get {
                return ResourceManager.GetString("Runtime_InvalidParserImplementationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name &apos;{0}&apos; has incorrect format..
        /// </summary>
        internal static string Runtime_InvalidPropertyNameFormat {
            get {
                return ResourceManager.GetString("Runtime_InvalidPropertyNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable name &apos;{0}&apos; has incorrect format..
        /// </summary>
        internal static string Runtime_InvalidVariableNameFormat {
            get {
                return ResourceManager.GetString("Runtime_InvalidVariableNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with name &apos;{0}&apos; not found..
        /// </summary>
        internal static string Runtime_ItemNotFound {
            get {
                return ResourceManager.GetString("Runtime_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected &apos;{0}&apos; mode of JavaScript engine is not supported!.
        /// </summary>
        internal static string Runtime_JsEngineModeNotSupported {
            get {
                return ResourceManager.GetString("Runtime_JsEngineModeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load a {0} JavaScript engine. Try to install the Internet Explorer {1} or higher.
        ///See more details:
        ///
        ///{2}.
        /// </summary>
        internal static string Runtime_JsEngineNotLoaded {
            get {
                return ResourceManager.GetString("Runtime_JsEngineNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is prohibited to use the Chakra JsRT and the Chakra ActiveScript on one machine at a time..
        /// </summary>
        internal static string Runtime_JsEnginesChakraJsRtAndActiveScriptConflict {
            get {
                return ResourceManager.GetString("Runtime_JsEnginesChakraJsRtAndActiveScriptConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not found none of the JavaScript engines. Perhaps you have not installed the Internet Explorer browser..
        /// </summary>
        internal static string Runtime_JsEnginesNotFound {
            get {
                return ResourceManager.GetString("Runtime_JsEnginesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name &apos;{0}&apos; is forbidden, as one of its parts matches with the reserved word of JavaScript language..
        /// </summary>
        internal static string Runtime_PropertyNameIsForbidden {
            get {
                return ResourceManager.GetString("Runtime_PropertyNameIsForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{1}&apos; of variable &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Runtime_PropertyNotExist {
            get {
                return ResourceManager.GetString("Runtime_PropertyNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{1}&apos; of variable &apos;{0}&apos; has a type `{2}`, which is not supported..
        /// </summary>
        internal static string Runtime_PropertyTypeNotSupported {
            get {
                return ResourceManager.GetString("Runtime_PropertyTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of return value `{0}` is not supported..
        /// </summary>
        internal static string Runtime_ReturnValueTypeNotSupported {
            get {
                return ResourceManager.GetString("Runtime_ReturnValueTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert to `{0}`. The type is unsupported..
        /// </summary>
        internal static string Runtime_TypeUnsupported {
            get {
                return ResourceManager.GetString("Runtime_TypeUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable name &apos;{0}&apos; is forbidden, as is contained in the list of reserved words of JavaScript language..
        /// </summary>
        internal static string Runtime_VariableNameIsForbidden {
            get {
                return ResourceManager.GetString("Runtime_VariableNameIsForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable with the name &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Runtime_VariableNotExist {
            get {
                return ResourceManager.GetString("Runtime_VariableNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable &apos;{0}&apos; has a type `{1}`, which is not supported..
        /// </summary>
        internal static string Runtime_VariableTypeNotSupported {
            get {
                return ResourceManager.GetString("Runtime_VariableTypeNotSupported", resourceCulture);
            }
        }
    }
}
