//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsieJavaScriptEngine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MsieJavaScriptEngine.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; must be a non-empty string..
        /// </summary>
        internal static string Common_ArgumentIsEmpty {
            get {
                return ResourceManager.GetString("Common_ArgumentIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; must be a non-nullable..
        /// </summary>
        internal static string Common_ArgumentIsNull {
            get {
                return ResourceManager.GetString("Common_ArgumentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} not exist..
        /// </summary>
        internal static string Common_FileNotExist {
            get {
                return ResourceManager.GetString("Common_FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null..
        /// </summary>
        internal static string Common_ValueIsNull {
            get {
                return ResourceManager.GetString("Common_ValueIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code.
        /// </summary>
        internal static string ErrorDetails_ErrorCode {
            get {
                return ResourceManager.GetString("ErrorDetails_ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCode.
        /// </summary>
        internal static string ErrorDetails_ErrorWCode {
            get {
                return ResourceManager.GetString("ErrorDetails_ErrorWCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help keyword.
        /// </summary>
        internal static string ErrorDetails_HelpKeyword {
            get {
                return ResourceManager.GetString("ErrorDetails_HelpKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line number.
        /// </summary>
        internal static string ErrorDetails_LineNumber {
            get {
                return ResourceManager.GetString("ErrorDetails_LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line source.
        /// </summary>
        internal static string ErrorDetails_LineSource {
            get {
                return ResourceManager.GetString("ErrorDetails_LineSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string ErrorDetails_Message {
            get {
                return ResourceManager.GetString("ErrorDetails_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory.
        /// </summary>
        internal static string ErrorDetails_Subcategory {
            get {
                return ResourceManager.GetString("ErrorDetails_Subcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource with name &apos;{0}&apos; is null..
        /// </summary>
        internal static string Resources_ResourceIsNull {
            get {
                return ResourceManager.GetString("Resources_ResourceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of the expression &apos;{0}&apos; is undefined..
        /// </summary>
        internal static string Runtime_ExpressionResultIsUndefined {
            get {
                return ResourceManager.GetString("Runtime_ExpressionResultIsUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function name &apos;{0}&apos; is forbidden, as is contained in the list of reserved words of JavaScript language..
        /// </summary>
        internal static string Runtime_FunctionNameIsForbidden {
            get {
                return ResourceManager.GetString("Runtime_FunctionNameIsForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function name &apos;{0}&apos; has incorrect format..
        /// </summary>
        internal static string Runtime_InvalidFunctionNameFormat {
            get {
                return ResourceManager.GetString("Runtime_InvalidFunctionNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parser you passed implements neither IActiveScriptParse32 nor IActiveScriptParse64..
        /// </summary>
        internal static string Runtime_InvalidParserImplementationError {
            get {
                return ResourceManager.GetString("Runtime_InvalidParserImplementationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name &apos;{0}&apos; has incorrect format..
        /// </summary>
        internal static string Runtime_InvalidPropertyNameFormat {
            get {
                return ResourceManager.GetString("Runtime_InvalidPropertyNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable name &apos;{0}&apos; has incorrect format..
        /// </summary>
        internal static string Runtime_InvalidVariableNameFormat {
            get {
                return ResourceManager.GetString("Runtime_InvalidVariableNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with name &apos;{0}&apos; not found..
        /// </summary>
        internal static string Runtime_ItemNotFound {
            get {
                return ResourceManager.GetString("Runtime_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load none of the JavaScript engines. Perhaps you have not installed the Internet Explorer browser..
        /// </summary>
        internal static string Runtime_JsEngineNotLoaded {
            get {
                return ResourceManager.GetString("Runtime_JsEngineNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name &apos;{0}&apos; is forbidden, as one of its parts matches with the reserved word of JavaScript language..
        /// </summary>
        internal static string Runtime_PropertyNameIsForbidden {
            get {
                return ResourceManager.GetString("Runtime_PropertyNameIsForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert to &apos;{0}&apos;. The type is unsupported..
        /// </summary>
        internal static string Runtime_TypeUnsupported {
            get {
                return ResourceManager.GetString("Runtime_TypeUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable name &apos;{0}&apos; is forbidden, as is contained in the list of reserved words of JavaScript language..
        /// </summary>
        internal static string Runtime_VariableNameIsForbidden {
            get {
                return ResourceManager.GetString("Runtime_VariableNameIsForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable with the name of &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Runtime_VariableNotExist {
            get {
                return ResourceManager.GetString("Runtime_VariableNotExist", resourceCulture);
            }
        }
    }
}
